"""
Django settings for rabbitmq_demo project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#gkm*p@tn)*g*%y*94pln5%88s3j$sggmo9_zv9tfyl(_38*e4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks_app',
    'django_celery_results', # Store task result in DB
    'django_tasks_db',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rabbitmq_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rabbitmq_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@rabbitmqdemo.com'

# RabbitMQ & Celery Configuration
# RabbitMQ connection URL
# Format: amqp://username:password@hostname:port/virtual_host
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'

# Alternative with custom vhost:
# CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672/my_vhost'

# Result backend - store results in Django database
CELERY_RESULT_BACKEND = 'django-db'

# Task serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json', 'application/json']
CELERY_TIMEZONE = 'Africa/Kampala'
CELERY_ENABLE_UTC = False

# Task result expiration
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7 # 7 days

# RabbitMQ-Specific Settings
# Connection pool settings
CELERY_BROKER_POOL_LIMIT = 10

# Heartbeat settings (keep connection alive)
CELERY_BROKER_HEARTBEAT = 30

# Connection retry settings
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Message acknowledgement settings
CELERY_TASK_ACKS_LATE = True # Acknowledge tasks after completion, not when received
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # Only fetch one task at a time

# Task routing with RabbitMQ exchanges and queues
CELERY_TASK_ROUTES = {
    # Email tasks go to 'emails' queue
    'tasks_app.tasks.send_*': {
        'queue': 'emails',
        'routing_key': 'email.send',
    },
    # Processing tasks go to 'processing' queue
    'tasks_app.tasks.process_*': {
        'queue': 'processing',
        'routing_key': 'data.process',
    },
    # Reports go to 'reports' queue
    'tasks_app.tasks.generate_*': {
        'queue': 'reports',
        'routing_key': 'report.generate',
    },
}

# Define queues explicitly
from kombu import Exchange, Queue

CELERY_TASK_QUEUES = (
    # Default queue
    Queue('default', Exchange('default'), routing_key='default'),

    # Email queue with priority
    Queue('emails', Exchange('emails', type='direct'), routing_key='email.#'),

    # Processing queue
    Queue('processing', Exchange('processing', type='direct'), routing_key='data.#'),

    # Reports queue
    Queue('reports', Exchange('reports', type='direct'), routing_key='report.#'),

    # Priority queue for urgent tasks
    Queue('priority', Exchange('priority', type='direct'), routing_key='priority.#', queue_arguments={'x-max-priority': 10}),
)

# Default queue
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# Django Tasks Configuration - Using Celery with RabbitMQ
# TASKS = {
#     'default': {
#         # This package bridges Django tasks with Celery
#         'BACKEND': 'django_tasks_db.DatabaseBackend',
#     }
# }
TASKS = {
    'default': {
        # This package bridges Django tasks with Celery
        'BACKEND': 'django_tasks_celery.CeleryTaskBackend',
        'OPTIONS': {
            'celery_app_path': 'rabbitmq_demo.celery.app',
        }
    }
}



